spring.application.name=socialmediaapp
spring.profiles.active=dev
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8888}

app.jwt.access-token-expiration-minutes=15
app.jwt.refresh-token-expiration-days=7
