server:
  port: 8090

spring:
  application:
    name: gateway
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: follow-service
              uri: lb://FOLLOW-SERVICE
              order: 1
              predicates:
                - name: Path
                  args:
                    pattern: /api/follows/**
            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              order: 2
              predicates:
                - name: Path
                  args:
                    pattern: /api/notifications/**
            - id: activity-log-service
              uri: lb://ACTIVITY-LOG-SERVICE
              order: 3
              predicates:
                - name: Path
                  args:
                    pattern: /api/activity/**
            - id: user-service-auth
              uri: lb://USER-SERVICE
              order: 4
              predicates:
                - name: Path
                  args:
                    pattern: /api/auth/**
            - id: user-service-users
              uri: lb://USER-SERVICE
              order: 5
              predicates:
                - name: Path
                  args:
                    pattern: /api/users/**
            - id: content-service-posts
              uri: lb://CONTENT-SERVICE
              order: 100
              predicates:
                - name: Path
                  args:
                    pattern: /api/posts/**
            - id: content-service-comments
              uri: lb://CONTENT-SERVICE
              order: 101
              predicates:
                - name: Path
                  args:
                    pattern: /api/comments/**
            - id: content-service-likes
              uri: lb://CONTENT-SERVICE
              order: 102
              predicates:
                - name: Path
                  args:
                    pattern: /api/likes/**
