spring.application.name=user-service
server.port=8084
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8888}

spring.datasource.url=jdbc:postgresql://localhost:5436/userservice
spring.datasource.username=${DB_USERNAME:devuser}
spring.datasource.password=${DB_PASSWORD:devpass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

app.jwt.access-token-expiration-minutes=15
app.jwt.refresh-token-expiration-days=7
